[tool.poetry]
name = "django-message-alpine"
version = "0.1.0"
description = ""
authors = ["ImanHpr <imanhpr1999@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.0.6"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
